export const REDUCER_NAME = 'global';

export const GET_DRIVERS = `${REDUCER_NAME}/GET_DRIVERS`;
export const SET_DRIVERS_DATA_OPTIONS = `${REDUCER_NAME}/SET_DRIVER_DATA_OPTIONS`;

export const GET_DRIVER_RACES = `${REDUCER_NAME}/GET_DRIVER_RACES`;
export const SET_DRIVER_RACE_OPTIONS = `${REDUCER_NAME}/SET_DRIVER_RACE_OPTIONS`;
